# This is a basic workflow to help you get started with Actions

name: cd-synapse
# Controls when the workflow will run
on:
  workflow_dispatch:
#Run only when the pull request is closed and it targets main branch
  # push:
    
  #   branches:
  #   - main
  #   paths-ignore:
  #     - '.github/**'
  #     - 'build/**'
  #     - 'README.md'
  #     - 'CODEOWNERS'

# Modify the default permissions granted to GITHUB_TOKEN.
permissions:
      id-token: write
      contents: write
      packages: write

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout local
        uses: actions/checkout@v3

      # - name: Stop Synapse Triggers
      #   run: |
      #     az synapse trigger stop --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"

      - name: Synapse workspace deployment
        uses: Azure/Synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: 'ws-synapse-tm'
          TemplateFile: './ws-synapse-tm/TemplateForWorkspace.json'
          ParametersFile: './ws-synapse-tm/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: 'DNA_Reporting'
          # clientId: ${{ secrets.CLIENT_ID }}
          # clientSecret: ${{ secrets.CLIENT_SECRET }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          DeleteArtifactsNotInTemplate: 'true'
          operation: 'deploy'

      - name: Start Synapse Triggers
        run: |
          az synapse trigger start --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"

      # runs-on: ubuntu-latest     
      # steps:
      #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #   - name: Checkout code
      #     uses: actions/checkout@v3
      #   - name: Deploy Azure Resource Manager (ARM) Template              
      #     # uses: Azure/arm-deploy@v1
      #   - uses: azure/synapse-workspace-deployment@release-1.0
      #     with:
      #       TargetWorkspaceName: ws-synapse-tm
      #       TemplateFile: './path of the TemplateForWorkspace.json'
      #       ParametersFile: './path of the TemplateParametersForWorkspace.json'
      #       OverrideArmParameters: './path of the parameters.yaml'
      #       environment: 'Azure Public'
      #       resourceGroup: 'target workspace resource group'
      #       clientId: ${{ secrets.AZURE_CLIENT_ID }}
      #       clientSecret:  ${{secrets.CLIENTSECRET}}
      #       subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #       tenantId: ${{ secrets.AZURE_TENANT_ID }}
      #       DeleteArtifactsNotInTemplate: 'true'
      #       managedIdentity: 'False'
