# This is a basic workflow to help you get started with Actions

name: cicd-dev
# Controls when the workflow will run
on:
  workflow_dispatch:
#Run only when the pull request is closed and it targets main branch
  push:
    
    branches:
    - main
    paths-ignore:
      - '.github/**'
      - 'build/**'
      - 'README.md'
      - 'CODEOWNERS'

# Modify the default permissions granted to GITHUB_TOKEN.
permissions:
      id-token: write
      contents: write
      packages: write

jobs: 
  deploy:
      runs-on: ubuntu-latest     
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Deploy Azure Resource Manager (ARM) Template              
          uses: Azure/arm-deploy@v1
